### PR TITLE
edit first two lines of section 1

### PR DESCRIPTION
**Pull request by kyoshiwara**
This is just practice.  More later.

### CODE REVIEW

**Comment by kyoshiwara** [comment]
One of the things I like about your book is the easy, conversational tone of the exposition.  I would like to see that style preserved while accommodating some of the issues that arise from addressing students in print rather than in person.

Because there are no visual or vocal clues to help the reader, it's important to make clear what are the central ideas and what are more secondary or parenthetical remarks.  The leaner and more concise an explanation can be, the better.  A lot of this can be achieved by standard grammatical techniques:  short, declarative sentences, preferring active to passive voice, omitting unnecessary qualifiers.

Another practice that can help defray "reader fatigue" is using elaboration sparingly.  While restating a point in different language can help a listener absorb ideas in real time, it can be confusing or distracting for a reader.

I'd like to continue offering suggestions based on these guidelines.  Would that be useful for you?

**Comment by mattboelkins** [comment]
Kathy, this is very helpful to me and I would like to proceed with you editing in this way.

That said, there is a technical detail I need to sort out before accepting any pull requests.  I want to talk with David about whether or not it would be best to do this work in a way that it gets merged to a branch different than master.  I want to think carefully about updating the HTML slightly for small errors as compared to updating it significantly for prose, as well as what the timeline is for getting this task complete.  I'll start a separate thread on the support listserv.  Hopefully we can make a decision within a week or so and then work apace from there.

**Comment by kyoshiwara** [comment]
Thanks for your response, Matt.  I am still very shaky using git hub, and wasn't sure if I even managed to send you anything, so sorry if it was messed up in any way.  So I will be very happy to hold off and let you and David sort out the best way to proceed.  I await further instructions.


Kathy


________________________________

**Comment by davidfarmer** [comment]
I also have some thoughts about how to make the editing process easier
and will send around an email as soon as I write it.  But there are
things that are not clear to me, but Rob and others will probably
have some ideas.

Stay tuned.

**Pull request closed without merging**
